### ISSUE TITLE
Symlinks should use relative paths

### ISSUE THREAD

**Issue by rhcarvalho** [stevekuznetsov/origin-ci-tool#8]
These symlinks are pointing to absolute paths in @stevekuznetsov's work environment:

- https://github.com/stevekuznetsov/origin-ci-tool/blob/63b98ad2bd27ab626a58a5c0153d25896fae135a/oct/ansible/oct/playbooks/make/roles
- https://github.com/stevekuznetsov/origin-ci-tool/blob/63b98ad2bd27ab626a58a5c0153d25896fae135a/oct/ansible/oct/playbooks/package/roles
- (possible others)

**Comment by stevekuznetsov** [comment]
What a rookie mistake on my end! Thanks for the catch :)

**Comment by stevekuznetsov** [comment]
Fixed in
```
6ffac1a5918f8ae40cc669a17a1bc4e10eabac2e Changed role symlinks to be relative to their directory
```
